version: '3.8'

networks:
  vk-net:
    driver: bridge

services:

  vk-db-exporter:
    container_name: vk-db-exporter
    image: prom/mysqld-exporter
    environment:
      DATA_SOURCE_NAME: "prometheus-exporter:0000@(vk-db:6633)/"
    ports:
      - "9104:9104"
    networks:
      - vk-net

  vk-prometheus:
    container_name: vk-prometheus
    image: prom/prometheus
    ports:
      - "9094:9090"
    volumes:
      - ./mount/prometheus:/etc/prometheus
    networks:
      - vk-net

  vk-grafana:
    container_name: vk-grafana
    image: grafana/grafana
    ports:
      - "9095:3000"
    networks:
      - vk-net

  vk-loki:
    container_name: vk-loki
    image: grafana/loki:2.9.1
    volumes:
      - ./mount/loki:/mnt/config
    command: -config.file=/mnt/config/loki-config.yaml
    ports:
      - "3100:3100"
    networks:
      - vk-net

  vk-promtail:
    container_name: vk-promtail
    image: grafana/promtail:2.9.1
    volumes:
      - ./mount/loki:/mnt/config
      - ./logs:/var/log
    command: -config.file=/mnt/config/promtail-config.yaml
    depends_on:
      - vk-net