version: '3.8'

services:

  pgrp-main-mariadb:
    container_name: play-day-db-container
    image: mariadb:10.8.3
    ports:
      - "6633:3306"
    environment: # 환경 변수 전달
      MYSQL_ROOT_PASSWORD: "0000" # root 패스워드 지정
      MYSQL_DATABASE: "play-day-db" # 초기 디비 생성
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

