version: '3.8'

networks:
  vk-net:
    driver: bridge

services:

  vk-main-db:
    container_name: vk-db
    image: mariadb:10.8.3
    user: "mysql:${GID}"
    ports:
      - "6633:6633"
    environment: # 환경 변수 전달
      MYSQL_ROOT_PASSWORD: "0000" # root 패스워드 지정
      MYSQL_DATABASE: "vk-db" # 초기 디비 생성
      MYSQL_TCP_PORT: 6633
    volumes:
      - ./mount/mariadb/my.conf:/etc/mysql/my.cnf
      - ./mount/mariadb/log:/home/mysql/log
    networks:
      - vk-net