server:
  port: 8791
spring:
  profiles:
    active: local
  application:
    name: visit-knowledge

  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always


management:
  endpoints:
    web:
      exposure:
        include: prometheus

Loggin:
  level:
    org.hibernate.SQL: debug


setting:
  document:
    max-size : 20
  schedule:
    cron: 0 0 9 ? * MON-FRI # 매일 오전 9시 0분 0초
