server:
  port: 8791
spring:
  profiles:
    active: prod
  application:
    name: visit-knowledge

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

#  sql:
#    init:
#      data-locations: classpath:data.sql # data.sql 위치
#      mode: always # data.sql 허용


Loggin:
  level:
    org.hibernate.SQL: debug

