spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://vk-db:6633/vk-db
    username: root
    password: '0000'

