server:
  port: 8791
spring:
  profiles:
    active: local
  application:
    name: vkestrel
  flyway:
    enabled: true
    baseline-on-migrate: true

  decorator:
    datasource:
      p6spy:
        enable-logging: true

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always


management:
  endpoints:
    web:
      exposure:
        include: prometheus

Loggin:
  level:
    org.hibernate.SQL: debug


setting:
  parser:
    max-size : 10 # 한번 파싱할때 10개 씩만
  document:
    max-size : 20
  schedule:
    cron: 0 0 9 ? * MON-FRI # 매일 오전 9시 0분 0초
