global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['10.0.0.160:8791']

  - job_name: mariadb
    static_configs:
      - targets: [ '10.0.0.160:9104' ]
