global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['vk:8791']

  - job_name: exporter
    static_configs:
      - targets: [ 'vk-db-exporter:9104' ]
