
name: code review
on: [psuh]

jobs:

  review:
    runs-on: ubuntu-latest
    steps:
      - name: reviewer run
        uses: birariro/chicken-code-review@1.0.0
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          gpt-key: ${{secrets.GPT_KEY}}
          trigger: "PUSH"
