
name: code review
on: [push]

jobs:

  review:
    runs-on: ubuntu-latest
    steps:
      - name: reviewer run
        uses: birariro/chicken-code-review@1.0.2
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          gpt-key: ${{secrets.GPT_KEY}}
          trigger: "PUSH"
          language: "KR"
